### ISSUE TITLE
If there are multiple best submissions, will the latest one be taken?

### ISSUE THREAD

**Issue by Zackhardtoname** [eecs-autograder/autograder.io#11]
"If there are multiple best submissions, will the latest one be taken? Wondering for fixing up some style after getting full points"

**Comment by james-perretta** [comment]
Yes, that's correct. If there are multiple best submissions, it will select
the most recent one.

I'll double check whether the UI docs mention this and add a sentence if
they don't.

**Comment by james-perretta** [comment]
Added an entry to "How tos and FAQ": https://eecs-autograder.github.io/autograder.io/how_tos.html#what-happens-if-a-student-has-multiple-best-submissions
