### ISSUE TITLE
Potential timestamp/timezone enhancements

### ISSUE THREAD

**Issue by james-perretta** [eecs-autograder/autograder.io#12]
As a quick fix, https://github.com/eecs-autograder/ag-website-vue/issues/442 made it so that all formatted timestamps include the timezone. However, timestamps are still converted to the user's local timezone, which is good in some situations and bad in others. 

One potential change is to add a "fixed timezone" field to the course settings. All timestamps within that course would be shown in that timezone. Note that this would be opt-in and the default behavior would be to use the local time.

Here is a list of the main scenarios where timestamps are used and an assessment of whether fixed or local timezone might be preferred:
- **Project Deadline - Instructors**
    - Since the course syllabus specifies the deadline in a specific timezone, a fixed timezone would likely be preferred (no conversion necessary from the user).
- **Project Deadline - Students**
    - Theoretically, we want the deadline to be comparable to the student's "wall clock" time so that they don't have to do a conversion. However, we've seen recently that students can still get tripped up by this (some timezones have the same abbreviation, and the timezone on, say, a student's phone and laptop might not match).
        - **Possible solution**: Display local and fixed timezone
            - This would kick in when using a fixed timezone and the local and fixed timezones are different
        - **Possible solution**: Display amount of time remaining until the deadline (e.g., "1 day, 8 hours, 5 minutes")
            - This would kick in when using a fixed timezone and the local and fixed timezones are different

- **Submission timestamps**
    - A fixed timezone makes it clearer where the "submission limit reset" point is and can therefore reduce confusion for staff looking up student submissions.
- **Graphs**
    - A fixed timezone is likely better here so that instructors can show the graphs to their student without changing their computer's timezone settings.

I'd love to hear what some other instructors think of this. @awdeorio @amirkamil @lslavice @jamesjuett @hoosierEE @lukefahr @liamoreilly @aposp @neiljohari, could you weigh in on:
- Given the option, would you chose local (the current behavior) or fixed timezone?
- Are there any compelling use cases I've left out of the list above?

**Comment by james-perretta** [comment]
Alternate idea for making it clear to students when the deadline is coming up: If the local timezone is different from the course timezone, show the current time in the course timezone on the submit page.

**Comment by Faryab** [comment]
Is there not a way to make it so that only the course statistics graphs are in the "Course Timezone" but everything else stays as is?

**Comment by james-perretta** [comment]
That would certainly be possible, but I'd have to gather some additional feedback to see how widely that behavior is desired. Another way to accomplish what you describe would be to add a "select timezone" dropdown menu to the graph itself that can be used to show the graph in whatever timezone you want without changing your computer's timezone settings. I'd imagine it would be a bit confusing for someone to set their course timezone but then have some things display in that timezone and other things display in the local timezone.

**Comment by james-perretta** [comment]
(Consolidated some of the conversation into the original post)

**Comment by awdeorio** [comment]
Perhaps a simpler solution would be to always display time-until-deadline on the student interface.  That sounds easier to implement that a case-by-case kind of thing.  The Moment JS library and Python's Arrow library can do the time-to-string formatting easily.

Here's a couple of example of how it could look from a student perspective:
- Due on February 16, 2021, 08:00 PM EST (8 days)
- Due on February 8, 2021, 08:00 PM EST (4 hours)
- Due on February 8, 2021, 08:00 PM EST (52 minutes)
- Due on February 8, 2021, 08:00 PM EST (13 seconds)

**Comment by hoosierEE** [comment]
I like the idea that students should see a countdown until the project is due like @awdeorio wrote above.
When setting the due date and time, I want the interface to automatically detect my current timezone by default.
However, in case I set the due date while traveling (remember traveling? from the before times?) a manual override to edit the timezone would be good.

**Comment by james-perretta** [comment]
Here are some screenshots of "time until deadline" as I've implemented it so far. It updates automatically roughly once a minute.

![countdown-1](https://user-images.githubusercontent.com/4098992/114596597-d424b880-9c5d-11eb-9707-b961c93eb1cf.png)
![countdown-2](https://user-images.githubusercontent.com/4098992/114596610-d6871280-9c5d-11eb-961f-9ce5ba7f6ae9.png)
![countdown-3](https://user-images.githubusercontent.com/4098992/114596617-d850d600-9c5d-11eb-8806-9882d22a5bf1.png)
![countdown-4](https://user-images.githubusercontent.com/4098992/114596622-da1a9980-9c5d-11eb-8468-a95776eb0135.png)
![countdown-5](https://user-images.githubusercontent.com/4098992/114596788-0cc49200-9c5e-11eb-9fc6-00c8b90f8f72.png)
![countdown-6](https://user-images.githubusercontent.com/4098992/114596793-0f26ec00-9c5e-11eb-8660-4e989293d34e.png)

**Comment by james-perretta** [comment]
@hoosierEE It's fairly straightforward to add a timezone select field to the datetime picker, but it has a notable quirk:
![timezone-quirk](https://user-images.githubusercontent.com/4098992/114598116-86a94b00-9c5f-11eb-9643-6aa89838f61a.gif)

Notice how the section where the selected datetime is displayed as text always uses the local timezone. There isn't really a good way around this, and of course when you refresh the page it all ends up in the local timezone again. To me this seems fairly strange. What do the rest of you think?

**Comment by Faryab** [comment]
> @hoosierEE It's fairly straightforward to add a timezone select field to the datetime picker, but it has a notable quirk:
 
> Notice how the section where the selected datetime is displayed as text always uses the local timezone. There isn't really a good way around this, and of course when you refresh the page it all ends up in the local timezone again. To me this seems fairly strange. What do the rest of you think?

I think this can be interpreted as a feature rather than a bug. Personally, I like it this way since all I want to do is set the deadline in EDT. Everything else can be local time and is probably more convenient for me that way.

**Comment by Faryab** [comment]
How does time until deadline work for edge cases like <1 minute remaining? I'm concerned we will have angry students who say "I had <1 minute remaining when I submitted but used up a late day." 

Maybe one way to fix this would be to add a small (?) blurb next to it detailing that "this time updates every so often and should only be taken as an approximation. Make sure to submit the project before the listed deadline" or something along those lines?

**Comment by james-perretta** [comment]
> I think this can be interpreted as a feature rather than a bug. Personally, I like it this way since all I want to do is set the deadline in EDT. Everything else can be local time and is probably more convenient for me that way.

@Faryab I think I understand what you mean, but just to be extra sure, here is a screencap where my local time is PDT and I set the deadline in EDT:
![timezone-quirk](https://user-images.githubusercontent.com/4098992/114728232-e9a4eb80-9d0c-11eb-9182-82a1285bbb3d.gif)

**Comment by james-perretta** [comment]
> How does time until deadline work for edge cases like <1 minute remaining? I'm concerned we will have angry students who say "I had <1 minute remaining when I submitted but used up a late day."

Good point. To some extent, this issue already exists--if the clock on a student's computer says 11:59pm, but the server clock is already 12:00am, they would use a late day (or be unable to submit) even though the "submit" button doesn't say "use late day". That said, having an explicit "< 1 minute remaining" does feel more "official," and I could definitely see it being interpreted the way you suggest. 

My recommended solution would be to put the hard deadline a few (i.e., 5-10) minutes after the soft deadline (280 has been doing this for a while now). E.g., the soft deadline is 11:59pm and the hard deadline is 12:06am. This strategy pretty much eliminates the issue (with or without a countdown) and seems to have the added benefit of reducing the number of "I tried submitting at 12:01am, please accept my submission, here are my files" emails.

Something else to consider: I could remove the "past due" text that shows up after the deadline.

> Maybe one way to fix this would be to add a small (?) blurb next to it detailing that "this time updates every so often and should only be taken as an approximation. Make sure to submit the project before the listed deadline" or something along those lines?

I'd prefer to avoid this approach except as a last resort--there's already a lot going on on the submission page, and to me this feels more "read the fine print" rather than improving the experience for students.

**Comment by Faryab** [comment]
> Something else to consider: I could remove the "past due" text that shows up after the deadline.

Yeah, the past due might cause confusion with a soft/hard deadline approach. 

> Maybe one way to fix this would be to add a small (?) blurb next to it detailing that "this time updates every so often and should only be taken as an approximation. Make sure to submit the project before the listed deadline" or something along those lines?

I forgot the soft/hard deadline approach when I made the previous comment. In that case, I don't think it would be a real problem.

**Comment by james-perretta** [comment]
The "time until deadline" feature is ready to go. Looks the same as what's in the screenshots, but with the "past due" removed. I'll hold off on merging it for about a week or so in case anyone has additional feedback.

**Comment by james-perretta** [comment]
ChartJS 3 seems to have fixed the limitations I was running into, and I've now been able to get graph ticks with the timezone included and shift + wheel to scroll:

![charts-zoom](https://user-images.githubusercontent.com/4098992/116255947-b9177580-a740-11eb-92e5-5e44dfa77995.gif)

**Comment by james-perretta** [comment]
I just deployed the changes discussed here and am closing this issue :tada: 
If any of you have additional thoughts, feel free to comment in this issue or open a new one if you have a new idea.
