### ISSUE TITLE
Require honor pledge still allows submit

### ISSUE THREAD

**Issue by awdeorio** [eecs-autograder/autograder.io#15]
It appears that the "Require honor pledge" setting fails to disallow a submit when the "type your uniqname" field is empty.

I expected some kind of error saying "you must sign the honor pledge" or somesuch.  I also expected it to verify that I actually typed my uniqname, not just some random text.

**Comment by james-perretta** [comment]
Is this when you try to submit or a student? The honor pledge signing intentionally doesn't do anything for admins and staff.

**Comment by awdeorio** [comment]
Ah, that is when I submit as myself.  I didn't expect a different behavior.
