### ISSUE TITLE
Error in "submission_limit_reset_timezone"

### ISSUE THREAD

**Issue by palefo** [eecs-autograder/autograder.io#19]
Hi,

Thanks for this awesome tool! I've started using it for an Intro. to programming class in Peru.

I was planning to use it for a second class, but I'm getting this error. Any indication how to approach this issue?

![image](https://user-images.githubusercontent.com/4333696/125224119-93573280-e292-11eb-92f8-820036cec4df.png)

Best,

Pablo Fonseca

**Comment by james-perretta** [comment]
@palefo Thanks for reporting this! This is an unfortunate side effect of https://github.com/eecs-autograder/ag-website-vue/issues/287. The client side code is detecting a particular timezone, but the server side library must not recognize that timezone. 

As a quick fix on your deployment, you can comment out this line of code (line 112 of src/components/course_admin/manage_projects/manage_projects.vue in the ag-website-vue code): https://github.com/eecs-autograder/ag-website-vue/pull/484/files#diff-8c0efc8c9cf0e0e352c00bd25114b4e347174190030d8caa4c24c689617da4f1R112

I'll be able to look into this further probably sometime next week, but in the meantime let me know if you run into trouble with the quick fix I suggested above.

Thanks!
James

**Comment by palefo** [comment]
Thanks a lot @james-perretta , the quickfix is working just fine!

**Comment by james-perretta** [comment]
@palefo Quick note, a permanent fix for this is part of the latest major release (2022.01.v1). Let me know if you run into this issue again :)
