### ISSUE TITLE
Image links in documentation are broken

### ISSUE THREAD

**Issue by jtakeshi-nd** [eecs-autograder/autograder.io#21]
Example: in docs/getting_started/adding_test_cases.rst, the first image link is to https://github.com/eecs-autograder/autograder.io/blob/c446c36ca9ccb9d1638ba8e6aca75988195b3191/pics/adding_test_cases/instructor_files.gif, which does not display, and following the link gives a 404.

**Comment by james-perretta** [comment]
I think this is just an issue with how Sphinx rendering works vs GitHub's automatic rendering of markdown and RST files (they resolve file paths differently). These docs aren't intended to be viewed on GitHub, but you can view the properly rendered documentation here: https://eecs-autograder.github.io/autograder.io/

Let me know if that helps : )
