### ISSUE TITLE
Can't get student submissions to show or download

### ISSUE THREAD

**Issue by lslavice** [eecs-autograder/autograder.io#27]
Hi James!

This is for ENGR 101, Fall 2021, Project 2. 

The submission for (redacted) was originally autograded and passed. Then, it turned out that they hadn't made a partnership correctly. So, I think we (our admin IA) added the partner manually after the project closed. 

We're trying to resolve a regrade request about the style/handgrading for this submission, but we're getting errors that the submission can't be displayed. We can't see it under the handgrading tab, view it from within the AG, or download the files. 

Can you help us to at least be able to SEE the student's code so we could assign a grade? Thanks!

**Comment by james-perretta** [comment]
Sure thing, I'll follow up over email :)
