### ISSUE TITLE
Error in handgrading interface for student who only has rejected submissions

### ISSUE THREAD

**Issue by amirkamil** [eecs-autograder/autograder.io#31]
In the handgrading interface, when selecting a student who has submissions that were all rejected by validation checks, an error occurs. The message is

> Error in "num_submissions": Group ###### has no submissions

Specific example: https://autograder.io/web/project/1312?current_tab=handgrading&current_student_lookup=301558

**Comment by james-perretta** [comment]
Good catch, and thanks for opening this. Do you agree that the desired behavior should be that this case is handled the same way as students with no submissions?

**Comment by amirkamil** [comment]
That sounds right to me. Thanks!

**Comment by broad-well** [comment]
@james-perretta, @Normanwqn and I would like to work on this issue (and potentially more issues here) as part of our coursework for [EECS 481](https://eecs481.org/hw6.html), Software Engineering. Our work will be in [my fork](https://github.com/broad-well/ag-website-vue).

**Comment by james-perretta** [comment]
@broad-well @Normanwqn All yours!

**Comment by Normanwqn** [comment]
Hi. We submitted this <a href="https://github.com/eecs-autograder/ag-website-vue/pull/509">pull request</a> to possibly address this bug

**Comment by james-perretta** [comment]
Noting here that this issue also affects groups with only "removed from queue" submissions
