### ISSUE TITLE
Feature Request: Allow "Comments" on Test Cases/Commands

### ISSUE THREAD

**Issue by jamesjuett** [eecs-autograder/autograder.io#32]
It would be nice if we could add some internal comments explaining complex design decisions in an autograder configuration. For example "this command removes instructor solution sources so that it is safe for the following commands to allow students to view standard output".

**Comment by james-perretta** [comment]
Seems reasonable enough. Would this need to be displayed anywhere other than the test case config?

**Comment by jamesjuett** [comment]
No, I don't think it would need to be displayed anywhere else.

**Comment by james-perretta** [comment]
@jamesjuett Just a note that I'm adding a version of this as part of #33. However, what I'm adding there will be shown to all staff alongside test results, whereas it sounds like what you're describing here is only for admins.
