### ISSUE TITLE
Feature Request: Allow Student-Facing "Description" on Test Suites, Test Cases, Commands

### ISSUE THREAD

**Issue by jamesjuett** [eecs-autograder/autograder.io#33]
There are often cases where it would be useful to have a short description that shows up when a student opens a test case. For example, on a public test suite "these are the same tests released with the project that you can run locally". There's probably an argument for this feature at each level of configuration - test suites, test cases, and individual commands.

**Comment by james-perretta** [comment]
Makes sense. Will take a small bit of thinking about how to display this nicely in the UI (e.g., inline or a tooltip?), but otherwise nothing technically difficult here.

**Comment by lslavice** [comment]
I would also like to add that if we could also nicely display feedback for each test case, that would really help us provide scalable support to students. For example, something like this: 

<img width="580" alt="image" src="https://github.com/eecs-autograder/autograder.io/assets/70032904/861ae6a6-c728-4f51-a1d8-4ba818599c0f">


(I made this in PrairieLearn, but PL doesn't have MATLAB so ENGR 101 still needs the autograder ;) ) 



Right now, I'm doing this in a REALLY hacky way by making the test case scripts print out some output that has the advice to students:

<img width="725" alt="image" src="https://github.com/eecs-autograder/autograder.io/assets/70032904/08202b11-abb2-4952-b4af-0ba04a6b0704">


But this is difficult to read and harder to maintain than if the feedback could be set within the AG interface (using markdown or something). 


@james-perretta is this kind of messaging for both test cases (what JJ was talking about) and feedback (what I'm talking about) possible for the Fall 2024 semester?

**Comment by james-perretta** [comment]
@lslavice Just a note that I'm starting work on this--hopefully shouldn't take more than a couple days.

**Comment by lslavice** [comment]
Awesome! Can’t wait to see what you come up with!!

**Comment by james-perretta** [comment]
@lslavice Here's an example of what it looks like so far. Still a bit of styling to add and a few more test cases to write, but I have the following implemented:
- Staff-only descriptions
- "Regular" descriptions, shown to students regardless of pass/fail
- Fail-only description, shown to students only when the test fails
- Markdown rendering

![image](https://github.com/user-attachments/assets/c94e7a55-7e10-4c47-a724-f17fd7fd0423)

**Comment by lslavice** [comment]
AAAAHHHHH OMG THIS LOOKS SO AWESOME!!!!!!!

Thank you thank you thank you!!!! This is going to make lots of stuff look
so much nicer and WORK so much nicer!!!


----
Laura K. Alford, PhD (she/her/hers)
Lecturer IV
Naval Architecture & Marine Engineering
University of Michigan
