### ISSUE TITLE
Upgrade Docker version used in deployment

### ISSUE THREAD

**Issue by CarsonHoffman** [eecs-autograder/autograder.io#37]
Hi!

I'm currently running into an issue where Ubuntu 22.04 uses certain syscalls that don't seem to be allowed in the version of Docker currently deployed alongside the site. More specifically, compiling a Go program fails with `runtime/cgo: pthread_create failed: Operation not permitted`, which from [this issue](https://github.com/containers/skopeo/issues/1501) seems to be related to the use of syscalls that older versions of Docker do not support. Ubuntu 20.04 works perfectly fine, but our student-facing images are on 22.04 and I'd like to refrain from bifurcating version support on the AG if possible. (To be clear: the version of Go distributed with each version is not the issue here—our image retrieves Go separately from Ubuntu's repos. Across both 1.18.2 and 1.17.10, 20.04 works while 22.04 does not.) I hope that a version bump is all that is necessary here, and it seems like it may be!

**Comment by james-perretta** [comment]
Good to know! I can do a version bump sometime in July when we're between terms. Could you email me a simple hello world program that I can use to verify that the version bump works? (help@autograder.io)

**Comment by MattyMay** [comment]
@james-perretta I'm having what I think is the same problem when installing Python dependencies during an Ubuntu 22.04 image build on the AG -- `pip` throws `RuntimeError: can't start new thread`. Any chance the Docker version will be bumped before the start of the semester?

**Comment by james-perretta** [comment]
@MattyMay sorry for the delay--I'll see if I can get this taken care of today.

**Comment by james-perretta** [comment]
@CarsonHoffman @MattyMay I've updated all of the grader nodes to docker 20.10, let me know if that solved the issue.

**Comment by MattyMay** [comment]
@james-perretta All good on my end. Thanks!
