### ISSUE TITLE
Can't submit files to ENGR 101 F22 Project 4

### ISSUE THREAD

**Issue by lslavice** [eecs-autograder/autograder.io#41]
Myself and students are getting this error: 

<img width="718" alt="Screen Shot 2022-11-22 at 12 39 54 PM" src="https://user-images.githubusercontent.com/70032904/203383859-f11876ca-3e82-4d6b-bb9a-aa511fbd9351.png">

Trying to submit the file for ENGR 101 Fall 2022 Project 4. We've refreshed the page and we're logged in. Anything else to try?

**Comment by nelsontm** [comment]
Same issue for EECS 370 Fall 2022 Project 4

**Comment by maximosnolan** [comment]
Issue Still persisting in EECS 370.

**Comment by lslavice** [comment]
looks like it's fixed now! Refresh and log back in

**Comment by james-perretta** [comment]
Hi all, The issue was that the OS on the main server kicked the filesystem into read-only mode (Don told me that this can happen due to transient disk errors or power bumps, for example). We rebooted the machine, and that resolved the issue. Thanks for your patience!

**Comment by lslavice** [comment]
IT Crowd still relevant! :) 

![image](https://user-images.githubusercontent.com/70032904/203405012-3413216b-b423-4e8e-9701-bfb33f0444c2.png)
